CREATE TABLE aposta (
	id SERIAL NOT NULL,	
	jogada INTEGER NOT NULL,
	aposta VARCHAR(32) NOT NULL,
	pessoa_id LONG NOT NULL
);

ALTER TABLE aposta ADD PRIMARY KEY (id);


CREATE TABLE vencedor (
	id SERIAL NOT NULL,
	aposta_id INT NOT NULL,
	horario TIMESTAMP NOT NULL
);

ALTER TABLE vencedor ADD PRIMARY KEY (id);

ALTER TABLE vencedor ADD CONSTRAINT FK_vencedor_aposta
FOREIGN KEY (aposta_id) REFERENCES aposta (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

CREATE TABLE pessoa (
	id SERIAL NOT NULL,
	nome VARCHAR(255),
	dataNascimento DATE,
	loguin VARCHAR(32) UNIQUE,
	senha VARCHAR(32)
);

ALTER TABLE pessoa ADD PRIMARY KEY (id);

