CREATE TABLE Aposta (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	aposta VARCHAR(32) NOT NULL,
	valor INTEGER NOT NULL
);

CREATE TABLE Ganhador (
	id SERIAL NOT NULL PRIMARY KEY,
	horario TIMESTAMP NOT NULL,
	aposta_id INTEGER NOT NULL,
	CONSTRAINT vencedor_aposta_FK
		FOREIGN KEY(aposta_id)
			REFERENCES aposta(id)
);